### ISSUE TITLE
Failure when doing git deployment

### ISSUE THREAD

**Issue by jeremymeng** [Azure-Samples/meanjs#5]
My deployment to Azure didn't succeed after running `git push azure
master`.

The errors I saw in the output are

```
remote: Omitting next output lines...
remote: Looking for app.js/server.js under site root.
remote: Invalid start-up command "gulp" in package.json. Please use the format "node <script relative path>".
remote: Using start-up script server.js
remote: Generated web.config.
```

and

```
remote: .................
remote:
remote: D:\home\site\wwwroot\node_modules\imagemin-pngquant\index.js:2
remote: An error has occurred during web site deployment.
remote: const execBuffer = require('exec-buffer');
remote: gulp failed
remote: ^^^^^
remote: SyntaxError: Use of const in strict mode.
remote:     at Module._compile (module.js:439:25)
remote:     at Object.Module._extensions..js (module.js:474:10)
remote:     at Module.load (module.js:356:32)
remote:     at Function.Module._load (module.js:312:12)
remote:     at Module.require (module.js:364:17)
remote:     at require (module.js:380:17)
remote:     at Object.<anonymous> (D:\home\site\wwwroot\gulpfile.js:20:14)
remote:     at Module._compile (module.js:456:26)
remote:     at Object.Module._extensions..js (module.js:474:10)
remote:     at Module.load (module.js:356:32)
remote:     at Function.Module._load (module.js:312:12)
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
To https://ymmeanjs.scm.azurewebsites.net/ymmeanjs.git
* [new branch]      master -> master
```

**Comment by mdauscher** [comment]
Hello, I'm seeing the same problem.  

Searching around I found this [link](https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-nodejs) to a very similar MSFT published tutorial but deploying to a Linux container. I tried it and got past the problem you described above. I can now connect to the webapp but I'm getting http Service Unavailable errors.  I'm now chasing that problem. 

PS. I'm a novice at this and using these tutorials as a learning tool.

**Comment by rajeshdh** [comment]
Did you find any solution to this? I am having the same issue.

**Comment by stevedcc** [comment]
I'm having exactly the same issues.  Not impressed that Microsoft haven't responded in almost 5 months.

**Comment by foolisheep** [comment]
I got the same issue. The tutorial should be updated!

**Comment by foolisheep** [comment]
You can change the start line in package.json to
`"start": "node node_modules/gulp/bin/gulp.js",`

This will unblock the deployment, but still get error:

> Start script "node_modules/gulp/bin/gulp.js" from package.json is not found.

I would like to fix it complete in future.

**Comment by elqolbi** [comment]
I found the same problem, I also found this problem

```
remote: npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
remote: npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
remote: npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
remote: npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
remote: npm WARN deprecated gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
remote: npm WARN deprecated gulp-header@1.8.2: gulp-header 1.x is deprecated and will no longer be updated, please update to 2.x
remote: .....
remote: npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer
To https://sarjanazure.scm.azurewebsites.net:443/sarjanazure.git
 * [new branch]      master -> master
```

**Comment by skryshtafovych** [comment]
Any updates on this

**Comment by ghost** [comment]
Yikes. No update, huh? :(

**Comment by matthewkooshad** [comment]
i would like to use this project, but i'm getting blocked by this also. how to solve?
