### ISSUE TITLE
Issue Running the Application

### ISSUE THREAD

**Issue by Abbyreilly01** [Azure-Samples/meanjs#7]
Does anyone get this issue when starting the application?

**_[15:44:31] [nodemon] clean exit - waiting for changes before restart_**

It seems to just hang here.

Thanks for your time!
-----------------------------------------------------------------------------------------------------

c:\Program Files\MongoDB\Server\3.6\bin\meanjs>npm start

> meanjs@0.5.0 start c:\Program Files\MongoDB\Server\3.6\bin\meanjs
> gulp

[15:44:23] Using gulpfile c:\Program Files\MongoDB\Server\3.6\bin\meanjs\gulpfile.js
[15:44:23] Starting 'default'...
[15:44:23] Starting 'env:dev'...
[15:44:23] Finished 'env:dev' after 249 μs
[15:44:23] Starting 'copyLocalEnvConfig'...
[15:44:23] Starting 'makeUploadsDir'...
[15:44:23] Finished 'makeUploadsDir' after 961 μs
[15:44:23] Finished 'copyLocalEnvConfig' after 18 ms
[15:44:23] Starting 'lint'...
[15:44:23] Starting 'less'...
[15:44:23] Finished 'less' after 562 ms
[15:44:23] Starting 'sass'...
[15:44:24] Finished 'sass' after 33 ms
[15:44:24] Starting 'csslint'...
[15:44:24] Starting 'eslint'...
[15:44:25] Finished 'csslint' after 1.21 s
[15:44:27] Finished 'eslint' after 3.31 s
[15:44:27] Finished 'lint' after 4 s
[15:44:27] Starting 'nodemon'...
[15:44:27] Finished 'nodemon' after 76 ms
[15:44:27] Starting 'watch'...
[15:44:27] Finished 'watch' after 249 ms
[15:44:27] Finished 'default' after 4.35 s
[15:44:27] [nodemon] 1.17.2
[15:44:27] [nodemon] to restart at any time, enter `rs`
[15:44:27] [nodemon] watching: modules/*/server/views/*.html server.js config/**/*.js modules/*/server/**/*.js modules/*/server/config/*.js
[15:44:27] [nodemon] watching extensions: js,html
[15:44:27] [nodemon] starting `node --inspect server.js`
[15:44:27] [nodemon] spawning
[15:44:27] [nodemon] child pid: 61260
Debugger listening on ws://127.0.0.1:9229/fb13957e-fb10-434b-a6f6-78c5a2c9fbdd
For help see https://nodejs.org/en/docs/inspector

**+ Important warning: config.domain is empty. It should be set to the fully qualified domain of the app.
[15:44:28] [nodemon] watching 548 files
Could not connect to MongoDB!**
{ MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (c:\Program Files\MongoDB\Server\3.6\bin\meanjs\node_modules\mongoose\node_modules\mongodb-core\lib\topologies\server.js:328:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (c:\Program Files\MongoDB\Server\3.6\bin\meanjs\node_modules\mongoose\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (c:\Program Files\MongoDB\Server\3.6\bin\meanjs\node_modules\mongoose\node_modules\mongodb-core\lib\connection\connection.js:177:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'MongoError',
  message: 'failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]' }
(node:63076) UnhandledPromiseRejectionWarning: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (c:\Program Files\MongoDB\Server\3.6\bin\meanjs\node_modules\mongoose\node_modules\mongodb-core\lib\topologies\server.js:328:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (c:\Program Files\MongoDB\Server\3.6\bin\meanjs\node_modules\mongoose\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (c:\Program Files\MongoDB\Server\3.6\bin\meanjs\node_modules\mongoose\node_modules\mongodb-core\lib\connection\connection.js:177:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:63076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:63076) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
**_[15:44:31] [nodemon] clean exit - waiting for changes before restart_**

**Comment by Abbyreilly01** [comment]
Resolved by open a new terminal and connecting to Mongo by running mongo.exe.  Once connected, reran the command in the existing terminal and connected fine.
